"""add consents.language for Law 25 traceability

Revision ID: 44e35921dfc7
Revises: 01def52b6aeb
Create Date: 2026-09-06 22:04:44.274566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44e35921dfc7'
down_revision: Union[str, None] = '01def52b6aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consents', sa.Column('language', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consents', 'language')
    # ### end Alembic commands ###
