"""initial schema

Revision ID: 62255e897608
Revises: 
Create Date: 2026-09-06 21:07:03.793653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '62255e897608'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_category'), 'providers', ['category'], unique=False)
    op.create_index(op.f('ix_providers_region'), 'providers', ['region'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_contact_method', sa.Enum('email', 'sms', 'phone', name='preferred_contact_method_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.Enum('record_video', 'send_email', 'send_sms', name='consent_type_enum'), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consents_user_id', 'consents', ['user_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'TRANSCRIBED', 'EXTRACTED', 'MATCHED', 'SENT', name='submission_status_enum'), server_default='UPLOADED', nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('language_detected', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submissions_user_id', 'submissions', ['user_id'], unique=False)
    op.create_table('extracted_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('problem_summary', sa.Text(), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', name='urgency_enum'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.String(length=64), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_extracted_problems_category'), 'extracted_problems', ['category'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('solution_text', sa.Text(), nullable=False),
    sa.Column('match_type', sa.Enum('provider', 'ai_generated', name='match_type_enum'), nullable=False),
    sa.Column('needs_human_review', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matches_submission_id', 'matches', ['submission_id'], unique=False)
    op.create_table('messages_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', name='message_channel_enum'), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('casl_consent_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', name='message_status_enum'), server_default='queued', nullable=False),
    sa.ForeignKeyConstraint(['casl_consent_id'], ['consents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_sent_casl_consent_id'), 'messages_sent', ['casl_consent_id'], unique=False)
    op.create_index('ix_messages_sent_submission_id', 'messages_sent', ['submission_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_queue_submission_id', 'review_queue', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_queue_submission_id', table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index('ix_messages_sent_submission_id', table_name='messages_sent')
    op.drop_index(op.f('ix_messages_sent_casl_consent_id'), table_name='messages_sent')
    op.drop_table('messages_sent')
    op.drop_index('ix_matches_submission_id', table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_extracted_problems_category'), table_name='extracted_problems')
    op.drop_table('extracted_problems')
    op.drop_index('ix_submissions_user_id', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_consents_user_id', table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_providers_region'), table_name='providers')
    op.drop_index(op.f('ix_providers_category'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###

    # Hand-added: autogenerate creates the native ENUM types implicitly via
    # create_table but never drops them, so without this a downgrade followed
    # by an upgrade fails with 'type "..._enum" already exists'.
    for enum_name in (
        'message_status_enum',
        'message_channel_enum',
        'match_type_enum',
        'urgency_enum',
        'submission_status_enum',
        'consent_type_enum',
        'preferred_contact_method_enum',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
