"""add hashed_password to users

Revision ID: 9f8ea66fa957
Revises: 62255e897608
Create Date: 2026-09-06 21:18:18.436120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9f8ea66fa957'
down_revision: Union[str, None] = '62255e897608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adjusted from autogenerate: adding a NOT NULL column outright fails on any
    # table that already has rows, so add it nullable, backfill, then constrain.
    op.add_column(
        'users', sa.Column('hashed_password', sa.String(length=255), nullable=True)
    )
    # '!' is passlib's unusable-password marker: it is not a valid hash, so
    # verify_password() can never match it and these accounts cannot log in
    # until a real password is set.
    op.execute("UPDATE users SET hashed_password = '!' WHERE hashed_password IS NULL")
    op.alter_column('users', 'hashed_password', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
