"""add matches.solution_json

Revision ID: ed8cd1b6b992
Revises: 28d69027b1a6
Create Date: 2026-09-07 11:28:45.731146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ed8cd1b6b992'
down_revision: Union[str, None] = '28d69027b1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('solution_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'solution_json')
    # ### end Alembic commands ###
